In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("data/candidate_summary_2022.csv")
df_2022 = df1.copy()
df_2022

,Link_Image,Cand_Name,Cand_Id,Cand_Office,Cand_Office_St,Cand_Office_Dist,Cand_Party_Affiliation,Cand_Incumbent_Challenger_Open_Seat,Total_Receipt,Total_Disbursement,...,Individual_Refund,Party_Committee_Refund,Other_Committee_Refund,Total_Contribution_Refund,Other_Disbursements,Net_Contribution,Net_Operating_Expenditure,Cash_On_Hand_BOP,Debt_Owe_To_Committee,Coverage_Start_Date
0,https://www.fec.gov/data/candidate/H2CA01185/?...,"GODFREY, MARCUS SCOTT",H2CA01185,H,CA,1.0,LIB,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,https://www.fec.gov/data/candidate/S2MO00502/?...,"NICHOLAS CRANE, STRAUSS",S2MO00502,S,MO,0.0,NaN,OPEN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,https://www.fec.gov/data/candidate/S2FL00532/?...,"PINNEY, DWAYNE",S2FL00532,S,FL,0.0,REP,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,https://www.fec.gov/data/candidate/H2AZ04200/?...,"DEHART, VAUGHAN BRANDON BRENDAN",H2AZ04200,H,AZ,4.0,REP,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,https://www.fec.gov/data/candidate/S2WI00367/?...,"NEUBERT, KEITH",S2WI00367,S,WI,0.0,REP,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4362,https://www.fec.gov/data/candidate/H2IL13187/?...,"TAYLOR, ELLIS EVERETT",H2IL13187,H,IL,13.0,DEM,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4363,https://www.fec.gov/data/candidate/H2PA05116/?...,"DEVAUGHN-GOODWIN, ALFEIA DEVAUGHN-GOOD",H2PA05116,H,PA,5.0,REP,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4364,https://www.fec.gov/data/candidate/H2CA28170/?...,"RODRIGUEZ, TONY",H2CA28170,H,CA,30.0,IND,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4365,https://www.fec.gov/data/candidate/H2IA04133/?...,"GROSSMAN, KYLE WILLIAM",H2IA04133,H,IA,4.0,LIB,CHALLENGER,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4366,https://www.fec.gov/data/candidate/H2IL01356/?...,"JONES, J DARNELL J.D.",H2IL01356,H,IL,1.0,DEM,OPEN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [3]:
cols = df_2022.columns

In [4]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4367 entries, 0 to 4366
Data columns (total 50 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Link_Image                            4367 non-null   object
 1   Cand_Name                             4367 non-null   object
 2   Cand_Id                               4367 non-null   object
 3   Cand_Office                           4367 non-null   object
 4   Cand_Office_St                        4367 non-null   object
 5   Cand_Office_Dist                      4264 non-null   float64
 6   Cand_Party_Affiliation                4363 non-null   object
 7   Cand_Incumbent_Challenger_Open_Seat   4240 non-null   object
 8   Total_Receipt                         4367 non-null   float64
 9   Total_Disbursement                    4367 non-null   float64
 10  Cash_On_Hand_COP                      4361 non-null   float64
 11  Debt_Owed_By_Committee                4350 non-null   float64
 12  Coverage_End_Date                     2609 non-null   object
 13  Cand_Street_1                         4357 non-null   object
 14  Cand_Street_2                         631 non-null    object
 15  Cand_City                             4367 non-null   object
 16  Cand_State                            4366 non-null   object
 17  Cand_Zip                              4360 non-null   float64
 18  Individual_Itemized_Contribution      4367 non-null   float64
 19  Individual_Unitemized_Contribution    4367 non-null   float64
 20  Individual_Contribution               4367 non-null   float64
 21  Other_Committee_Contribution          4367 non-null   float64
 22  Party_Committee_Contribution          4367 non-null   float64
 23  Cand_Contribution                     4367 non-null   float64
 24  Total_Contribution                    4367 non-null   float64
 25  Transfer_From_Other_Auth_Committee    4367 non-null   float64
 26  Cand_Loan                             4367 non-null   float64
 27  Other_Loan                            4367 non-null   float64
 28  Total_Loan                            4367 non-null   float64
 29  Offsets_To_Operating_Expenditure      4367 non-null   float64
 30  Offsets_To_Fundraising                4367 non-null   int64
 31  Offsets_To_Leagal_Accounting          4367 non-null   int64
 32  Other_Receipts                        4367 non-null   float64
 33  Operating_Expenditure                 4367 non-null   float64
 34  Exempt_Legal_Accounting_Disbursement  4367 non-null   int64
 35  Fundraising_Disbursement              4367 non-null   int64
 36  Transfer_To_Other_Auth_Committee      4367 non-null   float64
 37  Cand_Loan_Repayment                   4367 non-null   float64
 38  Other_Loan_Repayment                  4367 non-null   float64
 39  Total_Loan_Repayment                  4367 non-null   float64
 40  Individual_Refund                     4367 non-null   float64
 41  Party_Committee_Refund                4367 non-null   float64
 42  Other_Committee_Refund                4367 non-null   float64
 43  Total_Contribution_Refund             4367 non-null   float64
 44  Other_Disbursements                   4367 non-null   float64
 45  Net_Contribution                      4367 non-null   float64
 46  Net_Operating_Expenditure             4367 non-null   float64
 47  Cash_On_Hand_BOP                      4358 non-null   float64
 48  Debt_Owe_To_Committee                 4344 non-null   float64
 49  Coverage_Start_Date                   2609 non-null   object
dtypes: float64(33), int64(4), object(13)
memory usage: 1.7+ MB

In [5]:
df_2022 ['raised_from_pacs'] = df_2022['Other_Committee_Contribution'] + df_2022['Party_Committee_Contribution'] + df_2022['Transfer_From_Other_Auth_Committee']

In [6]:
df_2022 = df_2022.rename(columns={"Cand_Name": "first_last_party", "Cand_Party_Affiliation": "party", "Cand_Incumbent_Challenger_Open_Seat": "crpico", "Individual_Contribution": "raised_from_individuals", "Total_Contribution": "raised_total", "Individual_Unitemized_Contribution": "raised_unitemized"})

In [7]:
df_2022.columns

Index(['Link_Image', 'first_last_party', 'Cand_Id', 'Cand_Office',
       'Cand_Office_St', 'Cand_Office_Dist', 'party', 'crpico',
       'Total_Receipt', 'Total_Disbursement', 'Cash_On_Hand_COP',
       'Debt_Owed_By_Committee', 'Coverage_End_Date', 'Cand_Street_1',
       'Cand_Street_2', 'Cand_City', 'Cand_State', 'Cand_Zip',
       'Individual_Itemized_Contribution', 'raised_unitemized',
       'raised_from_individuals', 'Other_Committee_Contribution',
       'Party_Committee_Contribution', 'Cand_Contribution', 'raised_total',
       'Transfer_From_Other_Auth_Committee', 'Cand_Loan', 'Other_Loan',
       'Total_Loan', 'Offsets_To_Operating_Expenditure',
       'Offsets_To_Fundraising', 'Offsets_To_Leagal_Accounting',
       'Other_Receipts', 'Operating_Expenditure',
       'Exempt_Legal_Accounting_Disbursement', 'Fundraising_Disbursement',
       'Transfer_To_Other_Auth_Committee', 'Cand_Loan_Repayment',
       'Other_Loan_Repayment', 'Total_Loan_Repayment', 'Individual_Refund',
       'Party_Committee_Refund', 'Other_Committee_Refund',
       'Total_Contribution_Refund', 'Other_Disbursements', 'Net_Contribution',
       'Net_Operating_Expenditure', 'Cash_On_Hand_BOP',
       'Debt_Owe_To_Committee', 'Coverage_Start_Date', 'raised_from_pacs'],
      dtype='object')

In [8]:
cols_keep = ['first_last_party', 'party', 'crpico', 'raised_from_pacs', 'raised_from_individuals', 'raised_total', 'raised_unitemized']
df_2022 = df_2022[cols_keep]
df_2022.sample(5)

,first_last_party,party,crpico,raised_from_pacs,raised_from_individuals,raised_total,raised_unitemized
705,"DUNN, JAMES",REP,CHALLENGER,0.0,0.00,0.00,0.00
998,"CANNON, BEAU ALEXANDER RYAN MR",DEM,CHALLENGER,0.0,523.00,523.00,523.00
234,"MEADOWS, SAMANTHA",DEM,CHALLENGER,0.0,0.00,0.00,0.00
4125,"BEYER, DONALD STERNOFF HONORABLE JR.",DEM,INCUMBENT,467475.0,1201199.28,1668674.28,104946.92
2869,"FORE, JESSICA ALLISON",DEM,OPEN,0.0,14649.00,14649.00,6399.00

In [9]:
rep = {
    'REP': 'R',
    'DEM': 'D',
    'LIB': 'L',
    'IND': 'I',
    'N': 'U',
    'CHALLENGER': 'C',
    'OPEN': 'O',
    'INCUMBENT': 'I',    
}
df_2022 = df_2022.replace(rep)
df_2022.sample(5)

,first_last_party,party,crpico,raised_from_pacs,raised_from_individuals,raised_total,raised_unitemized
2524,"DERBY, DAVID",R,O,500.0,38150.00,38650.00,2000.00
3008,"KOCINA, KEVIN",R,O,10000.0,18476.00,28476.00,4021.00
3418,"BRANDT, DAVID MR",I,C,0.0,0.00,0.00,0.00
3413,"SIVALINGAM, TEJASINHA",R,C,0.0,466.75,690.93,366.75
765,"ROCO, JOHN",R,NaN,0.0,0.00,0.00,0.00

In [10]:
for col in df_2022.columns:
    print(df_2022[col].value_counts())

BERMAN, JOHN                          8
YOUNG, ALEEM MR                       6
RAMOS, JUAN                           5
GRAYSON, RICHARD                      5
MEDINA, IAN ANTHONY                   4
                                     ..
SALAZAR, GIRIEN RICARDO 2104738228    1
LENTZ, GREG                           1
BACON, ROGER                          1
FLORES-GIBSON, MARTHA ELENA DR        1
JONES, J DARNELL J.D.                 1
Name: first_last_party, Length: 4261, dtype: int64
R      2110
D      1551
I       162
L       123
ICD      89
OTH      41
NPA      34
UN       33
W        31
NNE      27
DFL      24
U        14
GRE      13
CON      11
NOP       9
NON       9
UND       8
AIP       8
UNK       7
CRV       6
FED       6
COM       5
IAP       4
FRE       2
PFP       2
IDP       2
LBL       2
WI        2
PRO       2
GOP       2
VET       2
US        1
CA        1
FLP       1
HRP       1
UC        1
RNC       1
UP        1
SLP       1
APF       1
UPP       1
IGD       1
11        1
GWP       1
UST       1
AKI       1
REF       1
EMP       1
PCH       1
GRN       1
ALL       1
PAF       1
AL        1
Name: party, dtype: int64
C    2882
O     947
I     411
Name: crpico, dtype: int64
0.00         3078
1000.00        41
500.00         38
5000.00        30
2000.00        29
             ...
354275.00       1
147377.59       1
79400.00        1
434090.01       1
281390.00       1
Name: raised_from_pacs, Length: 946, dtype: int64
0.0          1924
200.0           7
25.0            6
5000.0          5
50.0            4
             ...
26901.5         1
175991.0        1
2001.0          1
1458430.5       1
9585.0          1
Name: raised_from_individuals, Length: 2378, dtype: int64
0.00          1864
5000.00          5
1000.00          5
25.00            4
100.00           4
              ...
1372844.23       1
930907.12        1
731072.70        1
2918794.18       1
12725.77         1
Name: raised_total, Length: 2451, dtype: int64
0.00         1987
200.00         14
100.00         13
150.00          9
50.00           9
             ...
1601.50         1
1900.00         1
7469.41         1
531394.30       1
385.00          1
Name: raised_unitemized, Length: 2226, dtype: int64

In [11]:
# list of values to replace if not in
X = ['R','D','L','I','U']
# replace all values in row not in X with '3'
df_2022.loc[~df_2022.party.isin(X), 'party'] = '3'

In [12]:
party = df_2022['party'].value_counts()
party

R    2110
D    1551
3     407
I     162
L     123
U      14
Name: party, dtype: int64

In [13]:
(df_2022['raised_total'] == 0).sum()

1864

In [14]:
df_2022.fillna('', inplace=True)

In [15]:
df_2022.head()

,first_last_party,party,crpico,raised_from_pacs,raised_from_individuals,raised_total,raised_unitemized
0,"GODFREY, MARCUS SCOTT",L,C,0.0,0.0,0.0,0.0
1,"NICHOLAS CRANE, STRAUSS",3,O,0.0,0.0,0.0,0.0
2,"PINNEY, DWAYNE",R,C,0.0,0.0,0.0,0.0
3,"DEHART, VAUGHAN BRANDON BRENDAN",R,C,0.0,0.0,0.0,0.0
4,"NEUBERT, KEITH",R,C,0.0,0.0,0.0,0.0

In [16]:
df_2022.to_csv('data/cand_summary_2022_clean.csv', index=False)